# frozen_string_literal: true

source 'https://rubygems.org'

gem 'awspec'
gem 'confidante'
gem 'git'
gem 'nokogiri', '>= 1.19.4'
gem 'rake'
gem 'rake_factory', '~> 0.33.0'
gem 'rake_git', '~> 0.2.0'
gem 'rake_git_crypt', '~> 0.4.0'
gem 'rake_github'
gem 'rake_gpg'
gem 'rake_slack', '~> 0.3'
gem 'rake_terraform'
gem 'rspec'
gem 'rspec-terraform'
gem 'rubocop'
gem 'rubocop-rake'
gem 'rubocop-rspec'
gem 'ruby_git_crypt', '~> 0.1.0'
gem 'ruby_gpg2', '~> 0.12.0'
gem 'rubyzip'
gem 'semantic'
