# frozen_string_literal: true

source 'https://rubygems.org'

gem 'awspec'
gem 'confidante'
gem 'git'
gem 'nokogiri'
gem 'rake'
gem 'rake_git'
gem 'rake_git_crypt'
gem 'rake_github'
gem 'rake_gpg'
gem 'rake_slack'
gem 'rake_terraform'
gem 'rspec'
gem 'rspec-terraform'
gem 'rubocop'
gem 'rubocop-rake'
gem 'rubocop-rspec'
gem 'rubyzip'
gem 'semantic'
